@startuml
skinparam actorStyle actor
left to right direction
actor Auteur as Auteur
actor Lecteur as Lecteur
actor Administrateur as Admin

rectangle "Cas d'Utilisation" {
  (S'Authentifier)
  (Gérer Utilisateurs)
  (Gérer Livres)
  (Consulter Livres)
  (Barre de Recherche)
  (Gérer Son Compte)
  (Gérer Les Membres)
}

Auteur --> (S'Authentifier)
Auteur --> (Consulter Livres)
Auteur --> (Gérer Livres)
Lecteur --> (S'Authentifier)
Lecteur --> (Consulter Livres)
Admin --> (S'Authentifier)
Admin --> (Consulter Livres)
Admin --> (Gérer Utilisateurs)
Admin --> (Gérer Livres)
Auteur --> (Gérer Son Compte)
Lecteur --> (Gérer Son Compte)
Admin --> (Gérer Son Compte)
Admin --> (Gérer Les Membres)

(S'Authentifier) --> (Accéder au Site)
(S'Authentifier) --> (Accès Non Autorisé)
(Gérer Utilisateurs) --> (Créer Utilisateur)
(Gérer Utilisateurs) --> (Modifier Utilisateur)
(Gérer Utilisateurs) --> (Supprimer Utilisateur)
(Gérer Utilisateurs) --> (Consulter Profil Utilisateur)
(Consulter Livres) --> (Télécharger Livre)
(Consulter Livres) --> (Lire Livre)
(Gérer Livres) --> (Téléverser Livre)
(Gérer Livres) --> (Supprimer Livre)
(Barre de Recherche) --> (Trouver Livre)
(Barre de Recherche) --> (Afficher Résultats)

@enduml
